import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const read = (file) => readFileSync(resolve(root, file), "utf8");
const files = {
  pkg: read("package.json"),
  canvas: read("client/src/components/GameCanvas.tsx"),
  scene: read("client/src/game/scene.ts"),
  world: read("client/src/game/GameWorld.ts"),
  audio: read("client/src/game/AudioDirector.ts"),
  input: read("client/src/game/InputManager.ts"),
  hud: read("client/src/game/HudController.ts"),
  data: read("client/src/game/data.ts"),
  css: read("client/src/index.css"),
  html: read("client/index.html"),
  manifest: read("client/public/manifest.webmanifest"),
  capacitor: read("capacitor.config.ts"),
  android: read("android/app/src/main/AndroidManifest.xml"),
  plan: read("PLAN.md"),
  assets: read("ASSETS.md"),
};

const checks = [
  ["Dipendenza Babylon presente", "pkg", /"@babylonjs\/core"/],
  ["Bridge Capacitor presente", "pkg", /"@capacitor\/core"/],
  ["Piattaforma Android Capacitor presente", "pkg", /"@capacitor\/android"/],
  ["CLI Capacitor presente", "pkg", /"@capacitor\/cli"/],
  ["Script TypeScript disponibile", "pkg", /"check"\s*:\s*"tsc --noEmit"/],
  ["Script build disponibile", "pkg", /"build"\s*:/],
  ["Canvas a schermo intero", "canvas", /mn-game-root/],
  ["Canvas evita doppio mount", "canvas", /startedRef/],
  ["Motore viene creato", "canvas", /new Engine/],
  ["Resize è registrato", "canvas", /addEventListener\("resize"/],
  ["Resize è rimosso", "canvas", /removeEventListener\("resize"/],
  ["Handle viene distrutto", "canvas", /handle\?\.dispose/],
  ["Motore viene distrutto", "canvas", /engine\.dispose/],
  ["Render loop è vincolato alla scena", "canvas", /engine\.runRenderLoop/],
  ["Entrata scena definita", "scene", /createGameScene/],
  ["Handle tipizzato", "scene", /export type GameHandle/],
  ["Camera definita", "scene", /new FreeCamera/],
  ["Camera non acquisisce il puntatore", "scene", /camera\.inputs\.clear/],
  ["Illuminazione emisferica presente", "scene", /HemisphericLight/],
  ["Luce portuale direzionale presente", "scene", /DirectionalLight/],
  ["Update scena delega al mondo", "scene", /world\.update/],
  ["Dispose mondo esplicito", "scene", /world\.dispose/],
  ["Input semantico definito", "input", /export type InputIntent/],
  ["Sterzata sinistra tastiera", "input", /key === "a" \|\| key === "arrowleft"/],
  ["Sterzata destra tastiera", "input", /key === "d" \|\| key === "arrowright"/],
  ["Boost da tastiera", "input", /key === "w" \|\| key === "arrowup" \|\| key === " "/],
  ["Silenzio da tastiera", "input", /key === "s" \|\| key === "arrowdown"/],
  ["Pausa da tastiera", "input", /key === "p" \|\| key === "escape"/],
  ["Mute da tastiera", "input", /key === "m"/],
  ["Cooldown corsia presente", "input", /now - this\.lastLaneAt < 95/],
  ["Input blocca scorrimento frecce", "input", /event\.preventDefault/],
  ["Listener keyup rimosso", "input", /removeEventListener\("keyup"/],
  ["Stato menu esplicito", "world", /type Mode = "menu"/],
  ["Stato briefing esplicito", "world", /\| "briefing"/],
  ["Stato corsa esplicito", "world", /\| "running"/],
  ["Stato pausa esplicito", "world", /\| "paused"/],
  ["Stato officina esplicito", "world", /\| "garage"/],
  ["Stato debrief esplicito", "world", /\| "debrief"/],
  ["Tre corsie discrete", "world", /const LANES = \[-7, 0, 7\]/],
  ["Salvataggio locale nominato", "world", /marea-nera-operational-save-v3/],
  ["Compatibilità demo controllata", "world", /has\("demo"\)/],
  ["Auto avvio demo presente", "world", /if \(this\.demo\) window\.setTimeout/],
  ["Generatore deterministico demo", "world", /this\.randomSeed = \(this\.randomSeed \* 16807\)/],
  ["Pilota automatico demo", "world", /stepAutopilot/],
  ["Scafo gestito", "world", /private hull = 100/],
  ["Carburante gestito", "world", /private fuel = 100/],
  ["Intel gestita", "world", /private intel = 0/],
  ["Segnalatura gestita", "world", /private detection = 0\.12/],
  ["Invulnerabilità collisione gestita", "world", /this\.invulnerable = Math\.max\(0, this\.invulnerable - dt\)/],
  ["Deriva a serbatoio vuoto", "world", /private drift = 0/],
  ["Picco rilevazione tracciato", "world", /private peakDetection/],
  ["Boost consuma carburante", "world", /boost \? 5\.6 : 0/],
  ["Silenzio riduce segnalatura", "world", /silent\) this\.detection = Math\.max/],
  ["Boost aumenta segnalatura", "world", /boost\) this\.detection = Math\.min/],
  ["Carburante impedisce boost", "world", /const canBoost = this\.fuel > 5/],
  ["Deriva esaurimento carburante", "world", /CARBURANTE ESAURITO \/\/ DERIVA/],
  ["Danno da deriva prolungata", "world", /Il mare entra nello scafo/],
  ["Pursuit wave a segnalatura alta", "world", /ONDA D'INSEGUIMENTO/],
  ["Soglia di contatto alta", "world", /this\.detection > 0\.91/],
  ["Settori avanzano nel tempo", "world", /this\.sectorElapsed \+= dt/],
  ["Spawn legato al settore", "world", /spawnForSector\(sector\)/],
  ["Moltiplicatore minaccia per contatto", "world", /this\.detection > 0\.65 \? 1\.5 : 1/],
  ["Forca viene generata", "world", /spawnFork/],
  ["Risoluzione forca presente", "world", /resolveFork/],
  ["Rotta sicura abbassa segnale", "world", /ROTTA SICURA/],
  ["Rotta intel premia dati", "world", /ROUTE INTEL/],
  ["Rotta volatile genera inseguimento", "world", /ROUTE VOLATILE/],
  ["Estrazione è condizione di vittoria", "world", /if \(sector\.extract\)/],
  ["Soglia intel estrazione al 70%", "world", /Math\.ceil\(this\.chapter\.intelGoal \* 0\.7\)/],
  ["Sconfitta al collasso scafo", "world", /this\.hull <= 0/],
  ["Banca intel alla fine", "world", /this\.intelBank \+= banked/],
  ["Percentuale sconfitta ridotta", "world", /Math\.floor\(this\.intel \* 0\.4\)/],
  ["Acquisto moduli difeso", "world", /this\.intelBank < cost/],
  ["Moduli limitati a tre livelli", "world", /this\.modules\[id\] >= 3/],
  ["Run cleanup esplicito", "world", /cleanupRun/],
  ["Entità destrutte dopo passaggio", "world", /entity\.mesh\.dispose/],
  ["Barca giocatore è geometria leggibile", "world", /createBoat\("elias-boat"/],
  ["Pattuglia Black Tide è geometria leggibile", "world", /createBoat\("black-tide"/],
  ["Relitto è una geometria senza sfondo", "world", /CreateBox\("wreck"/],
  ["Custodia prova è una geometria senza sfondo", "world", /CreateBox\("intel-case"/],
  ["Tanica carburante è una geometria senza sfondo", "world", /CreateBox\("fuel-can"/],
  ["HUD costruito in DOM", "hud", /document\.createElement\("div"\)/],
  ["HUD usa aria-live", "hud", /aria-live="polite"/],
  ["HUD mostra scafo", "hud", /this\.meter\("SCAFO"/],
  ["HUD mostra carburante", "hud", /this\.meter\("CARBURANTE"/],
  ["HUD mostra intel", "hud", />INTEL</],
  ["HUD mostra segnalatura", "hud", />SEGNATURA</],
  ["HUD mostra radar", "hud", />RADAR</],
  ["HUD mostra trasmissione", "hud", /TRASMISSIONE/],
  ["HUD mostra stato boost", "hud", /BOOST \/\/ FIRMA IN AUMENTO/],
  ["HUD mostra stato silenzio", "hud", /SILENZIO \/\/ FIRMA IN CALO/],
  ["Controllo touch sinistra", "hud", /id="mn-left"/],
  ["Controllo touch destra", "hud", /id="mn-right"/],
  ["Controllo touch boost", "hud", /id="mn-boost"/],
  ["Controllo touch silenzio", "hud", /id="mn-silent"/],
  ["Controllo touch pausa", "hud", /id="mn-pause"/],
  ["Touch gestisce pointer cancel", "hud", /pointercancel/],
  ["Menu ha accesso briefing", "hud", /data-chapter/],
  ["Officina ha ritorno", "hud", /mn-garage-back/],
  ["Pausa ha ripresa", "hud", /mn-resume/],
  ["Pausa ha abbandono", "hud", /mn-quit/],
  ["Debrief ha riavvio", "hud", /mn-restart/],
  ["Stile riduce animazioni", "css", /prefers-reduced-motion/],
  ["Stile touch mobile presente", "css", /max-height: 500px\) and \(orientation: landscape\)/],
  ["Stile rotazione obbligatoria", "css", /orientation: portrait/],
  ["Stile safe area presente", "css", /safe-area-inset/],
  ["Manifest collegato", "html", /rel="manifest"/],
  ["Meta app mobile presente", "html", /mobile-web-app-capable/],
  ["Lingua italiana impostata", "html", /<html lang="it">/],
  ["Manifest fullscreen", "manifest", /"display": "fullscreen"/],
  ["Manifest landscape", "manifest", /"orientation": "landscape"/],
  ["Tema manifest corretto", "manifest", /"theme_color": "#041018"/],
  ["Nome manifest corretto", "manifest", /"short_name": "Marea Nera"/],
  ["ID Android definito", "capacitor", /appId: "com\.mareanera\.game"/],
  ["Web bundle definito", "capacitor", /webDir: "dist\/public"/],
  ["Sfondo Android coerente", "capacitor", /backgroundColor: "#041018"/],
  ["Manifest Android usa landscape", "android", /android:screenOrientation="landscape"/],
  ["Manifest Android abilita internet", "android", /android\.permission\.INTERNET/],
  ["Piano descrive test visivi", "plan", /cattura `\?demo`/],
  ["Manifest asset documentato", "assets", /marea-nera-evidence-case/],
  ["File Android di guida presente", null, () => existsSync(resolve(root, "ANDROID_PLAY_STORE.md"))],
  ["Otto capitoli narrativi presenti", "data", /export const CHAPTERS: Chapter\[\] = \[/],
  ["Capitolo 02 presente", "data", /LA CONTRABBANDIERA/],
  ["Capitolo 03 presente", "data", /ISOLA MORTA/],
  ["Capitolo 04 presente", "data", /CACCIA NELLA TEMPESTA/],
  ["Capitolo 05 presente", "data", /IL TRADIMENTO/],
  ["Capitolo 06 presente", "data", /IL PORTO NERO/],
  ["Capitolo 07 presente", "data", /title: "KROSS"/],
  ["Capitolo 08 presente", "data", /title: "MAREA NERA"/],
  ["Progresso capitoli salvato", "world", /unlockedChapterCount/],
  ["Selettore capitoli nel dossier", "hud", /mn-chapter-card/],
  ["Dossier bloccati segnalati", "hud", /SEGNALE BLOCCATO/],
  ["Debug capitolo per QA disponibile", "world", /debugChapter/],
  ["Simulazione allarme per QA disponibile", "world", /debugAlert/],
  ["Direttore audio definito", "audio", /export class AudioDirector/],
  ["Audio sblocca dopo gesto", "audio", /unlock\(\)/],
  ["Motore audio adattivo", "audio", /tick\(state/],
  ["Effetti audio nominati", "audio", /type AudioCue/],
  ["Radio usa sintesi vocale", "audio", /SpeechSynthesisUtterance/],
  ["Radio italiana impostata", "audio", /utterance\.lang = "it-IT"/],
  ["Mute interrompe la radio", "audio", /speechSynthesis\?\.cancel/],
  ["Audio pulito in dispose", "audio", /context\?\.close/],
];

if (checks.length < 100) throw new Error(`La suite deve avere almeno 100 controlli, ne ha ${checks.length}.`);
let failures = 0;
for (const [label, file, assertion] of checks) {
  const passed = typeof assertion === "function" ? assertion() : assertion.test(files[file]);
  process.stdout.write(`${passed ? "PASS" : "FAIL"} | ${label}\n`);
  if (!passed) failures += 1;
}
process.stdout.write(`\nRIEPILOGO: ${checks.length - failures}/${checks.length} controlli superati.\n`);
if (failures) process.exitCode = 1;
